import type { Metadata } from "next";
import { LegalLayout, LegalSection } from "@/components/legal/LegalLayout";
import { CheckCircle2 } from "lucide-react";

export const metadata: Metadata = {
  title: "Cookie Policy — VyaparMedia",
  description:
    "How VyaparMedia uses essential cookies, local storage, and service worker caches to secure authentication, facilitate payments, and power the PWA.",
};

const SECTIONS = [
  { id: "what-cookies-do", heading: "1. Purpose & Technologies" },
  { id: "categories", heading: "2. Cookie Categories We Use" },
  { id: "zero-tracking", heading: "3. Zero Cross-Site Tracking Guarantee" },
  { id: "pwa-storage", heading: "4. PWA Caching & Local Storage" },
  { id: "user-control", heading: "5. Browser Settings & User Control" },
  { id: "contact", heading: "6. Questions & Grievance Contact" },
];

const COOKIE_TYPES = [
  {
    name: "Essential Authentication Cookies",
    badge: "Strictly Necessary",
    badgeVariant: "purple",
    purpose:
      "Maintain secure signed-in sessions, CSRF token validation, role-based route guards, and 2FA TOTP challenges. The platform cannot function without these.",
  },
  {
    name: "Payment & Fraud Prevention",
    badge: "Financial Security",
    badgeVariant: "emerald",
    purpose:
      "Generated by Razorpay and internal risk monitors to authenticate card tokens, detect rapid automated attacks, and verify webhook signatures.",
  },
  {
    name: "User Preference Storage",
    badge: "Personalization",
    badgeVariant: "cyan",
    purpose:
      "Remembers dark/light theme choice, active dashboard view modes (grid vs list), and collapsed sidebar state across browser sessions.",
  },
  {
    name: "Performance & Diagnostic Telemetry",
    badge: "Reliability",
    badgeVariant: "amber",
    purpose:
      "Measures API response latencies, WebSocket reconnection health, and rendering errors to ensure reliable campaign deal rooms.",
  },
];

export default function CookiePage() {
  return (
    <LegalLayout
      title="Cookie Policy"
      lastUpdated="June 20, 2026"
      description="Transparent disclosure of the essential cookies, local web storage, and service worker caches used to power the VyaparMedia experience."
      sections={SECTIONS}
    >
      {/* 1 */}
      <LegalSection id="what-cookies-do" heading="1. Purpose &amp; Technologies">
        <p>
          VyaparMedia uses cookies and modern web storage mechanisms (including HTML5 LocalStorage, SessionStorage, and IndexedDB service worker caches) to provide a fast, secure, and reliable marketplace experience.
        </p>
        <p>
          These small data files are stored on your device when you access our web application or install the VyaparMedia Progressive Web App (PWA). They allow our systems to recognize your authenticated session and protect your escrow transactions.
        </p>
      </LegalSection>

      {/* 2 */}
      <LegalSection id="categories" heading="2. Cookie Categories We Use" highlight>
        <div className="space-y-4">
          {COOKIE_TYPES.map((c) => (
            <div key={c.name} className="rounded-xl border border-border bg-card p-4">
              <div className="flex items-center justify-between gap-2 mb-2">
                <h4 className="font-bold text-foreground text-sm">{c.name}</h4>
                <span
                  className={`text-2xs font-bold uppercase tracking-wider px-2 py-0.5 rounded-md border ${
                    c.badgeVariant === "purple"
                      ? "bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20"
                      : c.badgeVariant === "emerald"
                      ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20"
                      : c.badgeVariant === "cyan"
                      ? "bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-500/20"
                      : "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20"
                  }`}
                >
                  {c.badge}
                </span>
              </div>
              <p className="text-xs text-muted-foreground leading-relaxed">
                {c.purpose}
              </p>
            </div>
          ))}
        </div>
      </LegalSection>

      {/* 3 */}
      <LegalSection id="zero-tracking" heading="3. Zero Cross-Site Tracking Guarantee">
        <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-5 mb-4">
          <div className="flex items-center gap-2 font-bold text-foreground text-sm mb-1">
            <CheckCircle2 className="w-4 h-4 text-emerald-500" />
            <span>We Never Sell Your Browsing Data</span>
          </div>
          <p className="text-xs text-muted-foreground leading-relaxed">
            VyaparMedia does NOT deploy third-party advertising cookies, cross-site behavioral tracking pixels (like Meta Pixel or TikTok Pixel), or commercial data broker scripts. Your activity on VyaparMedia is private and never packaged for behavioral ad targeting.
          </p>
        </div>
      </LegalSection>

      {/* 4 */}
      <LegalSection id="pwa-storage" heading="4. PWA Caching &amp; Local Storage">
        <p>
          When you add VyaparMedia to your mobile or desktop home screen via our Progressive Web App (PWA), we cache application shell assets (fonts, icons, compiled CSS, and core UI JavaScript) using browser Service Workers.
        </p>
        <p>
          This enables instant load times on 4G/5G networks across India and allows offline viewing of previously loaded campaign briefs and contract drafts. You can wipe this cache at any time by uninstalling the PWA or clearing your browser site data.
        </p>
      </LegalSection>

      {/* 5 */}
      <LegalSection id="user-control" heading="5. Browser Settings &amp; User Control">
        <p>
          You have full control over cookie preferences through your web browser settings. Most browsers allow you to block third-party cookies, clear cookies upon browser exit, or inspect stored tokens.
        </p>
        <p className="text-xs text-muted-foreground">
          Please note: Blocking essential first-party cookies will prevent you from signing in, executing deals, or accessing your financial wallet.
        </p>
      </LegalSection>

      {/* 6 */}
      <LegalSection id="contact" heading="6. Questions &amp; Grievance Contact">
        <p>
          If you have questions regarding our use of cookies or web storage technologies, contact our technical privacy team:
        </p>
        <p className="mt-3">
          <a
            href="mailto:privacy@vyaparmedia.in"
            className="text-primary font-bold hover:underline inline-flex items-center gap-1.5"
          >
            privacy@vyaparmedia.in
          </a>
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
