-- ==============================================================================
-- Defense-in-Depth Row Level Security (RLS) Policies
-- Target: PostgreSQL / Supabase
-- Tables: Sensitive Financial Tables (Wallet, Transaction, Withdrawal, PaymentHold, BankAccount)
-- Purpose: Backstop & duplicate application-layer authorization directly in DB engine
-- ==============================================================================

-- 1. DUAL-CONTEXT AUTH RESOLVER FUNCTION
-- Resolves user ID whether incoming from Supabase Auth (JWT sub) or Prisma session context (app.current_user_id)
CREATE OR REPLACE FUNCTION get_current_actor_id() RETURNS TEXT AS $$
BEGIN
    RETURN COALESCE(
        NULLIF(current_setting('request.jwt.claim.sub', true), ''),
        NULLIF(current_setting('app.current_user_id', true), '')
    );
END;
$$ LANGUAGE plpgsql STABLE;


-- ==============================================================================
-- 2. WALLET POLICIES
-- ==============================================================================
ALTER TABLE "Wallet" ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS wallet_select_own ON "Wallet";
DROP POLICY IF EXISTS wallet_deny_client_insert ON "Wallet";
DROP POLICY IF EXISTS wallet_deny_client_update ON "Wallet";
DROP POLICY IF EXISTS wallet_deny_client_delete ON "Wallet";

-- Users can only read their own wallet
CREATE POLICY wallet_select_own ON "Wallet"
    FOR SELECT TO authenticated, anon
    USING ("userId" = get_current_actor_id());

-- Disallow client direct inserts, updates, and deletes (ledger balances must only be mutated by trusted server functions)
CREATE POLICY wallet_deny_client_insert ON "Wallet"
    FOR INSERT TO authenticated, anon
    WITH CHECK (false);

CREATE POLICY wallet_deny_client_update ON "Wallet"
    FOR UPDATE TO authenticated, anon
    USING (false);

CREATE POLICY wallet_deny_client_delete ON "Wallet"
    FOR DELETE TO authenticated, anon
    USING (false);


-- ==============================================================================
-- 3. TRANSACTION POLICIES (FINANCIAL LEDGER)
-- ==============================================================================
ALTER TABLE "Transaction" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS transaction_select_own ON "Transaction";
DROP POLICY IF EXISTS transaction_deny_client_insert ON "Transaction";
DROP POLICY IF EXISTS transaction_deny_client_update ON "Transaction";
DROP POLICY IF EXISTS transaction_deny_client_delete ON "Transaction";

-- Users can only read transactions belonging to their own wallet
CREATE POLICY transaction_select_own ON "Transaction"
    FOR SELECT TO authenticated, anon
    USING (
        "walletId" IN (
            SELECT w.id FROM "Wallet" w WHERE w."userId" = get_current_actor_id()
        )
    );

-- Transactions are append-only and strictly generated by server-side escrow flows
CREATE POLICY transaction_deny_client_insert ON "Transaction"
    FOR INSERT TO authenticated, anon
    WITH CHECK (false);

CREATE POLICY transaction_deny_client_update ON "Transaction"
    FOR UPDATE TO authenticated, anon
    USING (false);

CREATE POLICY transaction_deny_client_delete ON "Transaction"
    FOR DELETE TO authenticated, anon
    USING (false);


-- ==============================================================================
-- 4. WITHDRAWAL POLICIES
-- ==============================================================================
ALTER TABLE "Withdrawal" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS withdrawal_select_own ON "Withdrawal";
DROP POLICY IF EXISTS withdrawal_insert_pending_own ON "Withdrawal";
DROP POLICY IF EXISTS withdrawal_deny_client_update ON "Withdrawal";
DROP POLICY IF EXISTS withdrawal_deny_client_delete ON "Withdrawal";

-- Users can only view their own withdrawals
CREATE POLICY withdrawal_select_own ON "Withdrawal"
    FOR SELECT TO authenticated, anon
    USING (
        "walletId" IN (
            SELECT w.id FROM "Wallet" w WHERE w."userId" = get_current_actor_id()
        )
    );

-- Users can initiate a withdrawal only for their own wallet, locked to PENDING status
CREATE POLICY withdrawal_insert_pending_own ON "Withdrawal"
    FOR INSERT TO authenticated, anon
    WITH CHECK (
        status = 'PENDING' AND
        "walletId" IN (
            SELECT w.id FROM "Wallet" w WHERE w."userId" = get_current_actor_id()
        )
    );

-- Only backend service workers/admins can update withdrawal status (PROCESSING -> COMPLETED/FAILED)
CREATE POLICY withdrawal_deny_client_update ON "Withdrawal"
    FOR UPDATE TO authenticated, anon
    USING (false);

CREATE POLICY withdrawal_deny_client_delete ON "Withdrawal"
    FOR DELETE TO authenticated, anon
    USING (false);


-- ==============================================================================
-- 5. PAYMENT HOLD POLICIES (ESCROW DEPOSITS)
-- ==============================================================================
ALTER TABLE "PaymentHold" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS payment_hold_select_contract_parties ON "PaymentHold";
DROP POLICY IF EXISTS payment_hold_deny_client_mutation ON "PaymentHold";

-- Only the Brand and Influencer participating in the Deal can see the escrow hold
CREATE POLICY payment_hold_select_contract_parties ON "PaymentHold"
    FOR SELECT TO authenticated, anon
    USING (
        "dealId" IN (
            SELECT d.id FROM "Deal" d
            LEFT JOIN "BrandProfile" b ON d."brandId" = b.id
            LEFT JOIN "InfluencerProfile" i ON d."influencerId" = i.id
            WHERE b."userId" = get_current_actor_id() OR i."userId" = get_current_actor_id()
        )
    );

CREATE POLICY payment_hold_deny_client_mutation ON "PaymentHold"
    FOR ALL TO authenticated, anon
    USING (false);


-- ==============================================================================
-- 6. BANK ACCOUNT POLICIES (PII FINANCIAL DATA)
-- ==============================================================================
ALTER TABLE "BankAccount" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bank_account_select_own ON "BankAccount";
DROP POLICY IF EXISTS bank_account_insert_own ON "BankAccount";
DROP POLICY IF EXISTS bank_account_update_own ON "BankAccount";
DROP POLICY IF EXISTS bank_account_deny_client_delete ON "BankAccount";

-- Users can only view their own bank accounts
CREATE POLICY bank_account_select_own ON "BankAccount"
    FOR SELECT TO authenticated, anon
    USING ("userId" = get_current_actor_id());

-- Users can only add bank accounts for themselves (cannot verify penny-drop themselves)
CREATE POLICY bank_account_insert_own ON "BankAccount"
    FOR INSERT TO authenticated, anon
    WITH CHECK ("userId" = get_current_actor_id() AND "isVerified" = false);

CREATE POLICY bank_account_update_own ON "BankAccount"
    FOR UPDATE TO authenticated, anon
    USING ("userId" = get_current_actor_id())
    WITH CHECK ("userId" = get_current_actor_id());

-- Enforce soft-delete (prevent physical hard deletes)
CREATE POLICY bank_account_deny_client_delete ON "BankAccount"
    FOR DELETE TO authenticated, anon
    USING (false);


-- ==============================================================================
-- 7. SERVICE ROLE EXEMPTION
-- ==============================================================================
-- Ensure service_role (used by server-side Next.js / Prisma) retains full unrestricted access
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
        GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
        GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;
        GRANT ALL ON ALL ROUTINES IN SCHEMA public TO service_role;
    END IF;
END $$;
